"""add_is_active_to_workflow

Revision ID: ffaef69ba5ef
Revises: d720ba8c28c7
Create Date: 2026-05-16 11:27:38.435458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffaef69ba5ef'
down_revision: Union[str, None] = 'd720ba8c28c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'is_active')
    # ### end Alembic commands ###
